# Generated by Django 5.1.2 on 2024-12-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_personalinfo_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
