# Generated by Django 5.1.2 on 2024-12-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_personalinfo_secondphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='secondphone',
            new_name='second_phone',
        ),
    ]
