# Generated by Django 5.1.2 on 2024-12-28 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_rename_secondphone_personalinfo_second_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Language', 'Programming Language'), ('Framework', 'Framework'), ('Database', 'Database'), ('Technology', 'Technology')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='mainpage.personalinfo')),
            ],
        ),
    ]
